baseURL = 'https://drewdresser.com/'
languageCode = 'en-us'
title = 'Drew Dressers Weblog'
ignoreLogs = ['warning-goldmark-raw-html']

[Author]
    name = "Drew Dresser"
    email  = "andrewjdresser@gmail.com"

[taxonomies]
  tag = "tags"
[permalinks]
    blogmarks = "/:year/:month/:day/:slug/"
    posts = "/:year/:month/:day/:slug/"
