baseURL = 'https://drewdresser.com/'
languageCode = 'en-us'
title = 'Drew Dresser'
ignoreLogs = ['warning-goldmark-raw-html']

[taxonomies]
  tag = "tags"
[permalinks]
    blogmarks = "/:year/:month/:day/:slug/"
    posts = "/:year/:month/:day/:slug/"
